repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    - id: markdownlint-fix
      args: [--config,.markdownlint.jsonc]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0  # pick a git hash / tag to point to
    hooks:
    - id: editorconfig-checker
      alias: ec
